# Generated by Django 5.2.12 on 2026-04-10 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_profile_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_host',
            field=models.BooleanField(default=False),
        ),
    ]
