# Generated by Django 5.2.12 on 2026-04-22 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0007_propertybook_status_alter_propertybook_children_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertybook',
            name='stripe_session_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
